#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 21 11:59:44 2021

@author: mwa
"""
import matplotlib.pyplot as pp
import numpy as np
from tkinter import *
from PIL import Image, ImageTk

#Quand le bouton est pressé, on met à jour les valeurs
def trace_graphe1():
    x = np.linspace(0,100)
    fig = pp.figure()
    pp.plot(x, int(scale_lambda.get())*x*x)
    pp.savefig("fig1.png")
    render = ImageTk.PhotoImage(Image.open("fig1.png"))
    render_laser = ImageTk.PhotoImage(Image.open("frangesLaser.jpg"))
    img1 = Label(frame_HG, image=render)
    img1.image = render
    img1.grid(column=0, row=0)
    img2 = Label(frame_BG, image=render_laser)
    img2.image = render_laser
    img2.grid(column=0, row=0)
    img3 = Label(frame_BD, image=render)
    img3.image = render
    img3.grid(column=0, row=0)
    
    #selection = "Longueur d'onde = " + str(scale_lambda.get()) + " nm"
    #tex1.config(text = selection)
    
fenetre = Tk()


frame_HG = Frame(fenetre, )
frame_HD = Frame(fenetre)
frame_BG = Frame(fenetre)
frame_BD = Frame(fenetre)
frame_HG.grid(column=0, row=0)
frame_HD.grid(column=1, row=0)
frame_BG.grid(column=0, row=1)
frame_BD.grid(column=1, row=1)


bouton = Button(frame_HD, text='Changer valeur', command = trace_graphe1)
bouton.grid(column=0, row=3)

scale_lambda = Scale(frame_HD, orient=HORIZONTAL, label="Longueur d'onde")
scale_lambda.grid(column=0, row=0)
scale_lambda = Scale(frame_HD, orient=HORIZONTAL, label="Nombre de fentes")
scale_lambda.grid(column=0, row=1)

txt_contraste = Label(frame_HD, text="Contraste: []")
txt_contraste.grid(column=0, row=2)

fenetre.mainloop()
